name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "dckr_pat_-WjYCfSXRgsmhehmkWig48JO61g" | docker login -u lazardj --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t lazardj/test:${{ github.sha }} .
        docker push lazardj/test:${{ github.sha }}
