name: Dockerimage

on:
  push:
    branches: 
      - master

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Build the Docker image
      env:
        HUB_NAME: lazardj
        HUB_KEY: dckr_pat_-WjYCfSXRgsmhehmkWig48JO61g
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --file Dockerfile --tag zocker160/sheepit-client:latest

        docker tag zocker160/sheepit-client:latest zocker160/sheepit-client:nvidia

        docker push zocker160/sheepit-client:latest
        docker push zocker160/sheepit-client:nvidia

  vast:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Build the Docker image
      env:
        HUB_NAME: lazardj
        HUB_KEY: dckr_pat_-WjYCfSXRgsmhehmkWig48JO61g
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --file Dockerfile.vast --tag zocker160/sheepit-client:vast

        docker push zocker160/sheepit-client:vast
